version: '3.8' 

services: 
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    hostname: mariadb
    env_file: .env
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: always
    env_file: .env
    depends_on: 
      - mariadb

